<Interface>:
    orientation: 'vertical'
    
    Label:
        id: action
        text: 'Pedra Papel e Tesoura'
        font_size: 30
    
    Label:
        id: lbl_points
        text: ''
        font_size: 30
    
    Button:
        text: 'Rock'
        font_size: 30
        on_press: root.Rock()

    Button:
        text: 'Paper'
        font_size: 30
        on_press: root.Paper()
    
    Button:
        text: 'Scissor'
        font_size: 30
        on_press: root.Scissor()

    Button:
        id: btn_points
        text: 'Points'
        font_size: 30
        on_press: root.Points()